theme: jekyll-theme-minimal
title: Digital Security Champions
description: This is a hands-on guide for the Digital Security Champions Program. This is a Mozilla Foundation Alumni Connection Grant Project. 
logo: images/accessible.png
google_analytics: 
