theme: jekyll-theme-minimal
title: Accessible Online Security
description: A comprehensive guide to protecting yourself online. This is a Mozilla Open Leaders X Project.  
logo: images/accessible.png
